### PR TITLE
Adding local search with `@cmfcmf`-plugin

### PR DESCRIPTION
**Pull request by FilipHarald**
A first solution to #6

### CODE REVIEW

**Comment by FilipHarald** [comment]
Example:

https://github.com/user-attachments/assets/a497162c-db41-46f6-af2f-c385f4aee24d

**Comment by FilipHarald** [comment]
Used wrong branch. Will leave this PR in draft until #76 is done.

**Review by Pabl0cks — APPROVED** [review]
Thanks Filip for tackling this! 🙌 It's looking good to me! It's a basic search but I think it gets the job done. 

In terms of UI/UX has a couple of things that could be better, but they are nitpicks and probably it's not worth to invest the time in try to tweak the css from the plugin.

I've only pushed a nitpick in README (https://github.com/scaffold-eth/se-2-docs/pull/78/commits/014a1aabe7488e1d8d0948d9c9b0228c09766279) to try to make it more readable and a config setting (https://github.com/scaffold-eth/se-2-docs/pull/78/commits/decbb503be584761458622248964b8423d0fa0e8) to show category context in the search results modal:

| Before | After |
|--------|-------|
| Before configuration change | After configuration change |

**Comment by technophile-04** [comment]
Hey thanks @FilipHarald!! for tacking it! Looks good to me! 

Did you try using [easyops-cn/docusaurus-search-local](https://github.com/easyops-cn/docusaurus-search-local)? It seems a forked version of cmcf/search-local but with more stars and also some nitpicky good feature which were missing in cmcf/search-local example `cmd + k` to focus on search bar and also the search bar looks complete as compared to cmcf one also it seems to give better customisation options incase we need. 

could you also create an PR with [easyops-cn/docusaurus-search-local](https://github.com/easyops-cn/docusaurus-search-local)? I think it should be easy? since it seems like direct replacement to cmcf loca search?

**Comment by FilipHarald** [comment]
@technophile-04 , yup, I made a low-effort try and didn't get it to work. I wrote that here: https://github.com/scaffold-eth/se-2-docs/issues/6#issuecomment-2285977692 .

But I didn't look into it more then since I didn't know if it was going to be used. But I can do that now during the coming days :+1: . I will take @Pabl0cks improvements into account as well.

**Comment by technophile-04** [comment]
Hey @FilipHarald any updates on this? Also happy to merge this as it is! I think it gets the job done for now and we can always update later. 

A small nitpick(if it gets hard we could merge this as it is) but: 

Can me make this Search bar a bit bigger? 

Screenshot 2024-09-12 at 8 46 37 PM

Seem like it is too much cramped in 

And another `ctrl + k` or some keyboard shortcut to open it up. 

I would say don't waste lot of time on it, we could always iterate later but would be great if we get them working!

**Comment by FilipHarald** [comment]
Hello, sorry, no other things got in the way. I'll have a short look now on ctrl+k and sizing.

**Comment by FilipHarald** [comment]
@technophile-04 to be honest I kind on like having the search bar small, since you are not typing in it there anyway. But I've added width to it now. :+1:

**Comment by technophile-04** [comment]
> @technophile-04 to be honest I kind on like having the search bar small, since you are not typing in it there anyway. But I've added width to it now. 👍

Yup agree, it breaks on phone  too :( 

Screenshot 2024-09-12 at 9 20 11 PM

Let's revert that commit, we could update the styles later  🙌

**Comment by technophile-04** [comment]
Thanks @FilipHarald!! Lets keep iterating on this!!

**Pull request merged**
