### PR TITLE
Using tabs to split between Hardhat- and Foundry-environment

### PR DESCRIPTION
**Pull request by FilipHarald**
It's a bit ugly to get tabs to work with code-blocks in them. But perhaps it's worth it for the reader? Could also be possible to duplicate the doc entirely and just have two tabs for all of the info.

### CODE REVIEW

**Comment by FilipHarald** [comment]
How it looks:
https://github.com/user-attachments/assets/09dc5019-5520-4e83-bb04-84cf5f890999

**Comment by technophile-04** [comment]
Looks clean and nice!!! Just cc @Pabl0cks and @carletex  once they can check the demo [here](https://scaffold-eth-2-docs-45ul1sr66-buidlguidldao.vercel.app/quick-start/environment). 

also @FilipHarald could you please the fix the conflicts? incase we plan to go ahed with it we should also update https://docs.scaffoldeth.io/deploying/deploy-smart-contracts

**Comment by FilipHarald** [comment]
Updated `deploying/deploy-smart-contracts` :heavy_check_mark:

**Review by carletex — APPROVED** [review]
I dig it!! Good stuff @FilipHarald

**Review by Pabl0cks — APPROVED** [review]
Looks much cleaner for the user! TYSM @FilipHarald  🙌

**Pull request merged**
